######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 11 19:02:10 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += globj.h mainwindow.h
SOURCES += globj.cpp main.cpp mainwindow.cpp

 QT           += opengl
