######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 11 19:53:03 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h
SOURCES += dialog.cpp main.cpp
