######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 15 15:24:24 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h
SOURCES += dialog.cpp main.cpp
